module.exports = {
  title: 'Insert Into',
  tests: [
    `INSERT INTO test (col, cola, colb) values ('a', 2, 4, 'c')`,
    `INSERT INTO test (a, b1, c2) values ('abc', 222, 444, 'cccc')`,
    `INSERT INTO test (col_1, col_2, col_3 ) values ('a', 2, 4, 'c')`,
    `INSERT INTO test_a (col, cola, colb ) values ('a', 2, 4, 'c')`,
    // `INSERT INTO $test (col, cola, colb ) values ('a', 2, 4, 'c')`,
    `INSERT INTO test10 (col1, col2, col3 ) values ('a', 2, 4, 'c')`,
    `INSERT INTO test (col, cola, colb ) values ('a', 2, 4, 'c');`,
    `INSERT INTO test values (1, 'abc', 2, 4, 'c')`,
    `INSERT INTO test (col, cola, colb ) values ('a', 2, 4, 'c')`,
    `INSERT INTO test (col, cola, colb ) values ('a', 2, 4, 'c'), ('a', 2, 4, 'c')`,
    `INSERT INTO db.test (col, cola, colb ) values ('a', 2, 4, 'c'), ('a', 2, 4, 'c')`,
    `INSERT INTO \`db test\` (col, cola, colb ) values ('a', 2, 4, 'c'), ('a', 2, 4, 'c')`,
    `INSERT INTO \`db _test\` (col, cola, colb ) values ('a', 2, 4, 'c'), ('a', 2, 4, 'c')`,
    `INSERT INTO \`db\`\`test\` (col, cola, colb ) values ('a', 2, 4, 'c'), ('a', 2, 4, 'c')`,
    `INSERT INTO \`db"test\` (col, cola, colb ) values ('a', 2, 4, 'c'), ('a', 2, 4, 'c')`,
    `INSERT INTO "test" values ('a', 2, 4, 'c')`,
    `INSERT INTO "test_1" values ('a', 2, 4, 'c')`,
    `INSERT INTO \`test$\`.test values ('a', 2, 4, 'c')`,
    `INSERT INTO test values ('a b   c, de_fgh-ijk F123=@#;:?><.,+~\`\|[]{{}}plok ')`,
    `INSERT INTO test values ('a b '' cde ')`,
  ]
};